### PR TITLE
Display additional informations on Foundation members profiles

### PR DESCRIPTION
**Pull request by yleclanche**
Display more informations on foundation members profiles : 
- email (if the member allows it)
- social network and website links
- Plone use
- state

Original issue is here : https://github.com/plone/ploneorg.core/issues/235

### CODE REVIEW

**Comment by tkimnguyen** [comment]
@yleclanche thanks so much! and sorry for the delay getting back to you. The board discussed whether or not the Merit field should be shown publicly; the consensus is that the merit is part of the member's application and describes their contributions at that point in time, and it is unlikely they are going to want to keep it updated (nor do we have a mechanism for allowing them to edit it at the moment). So we should keep the Merit field's visibility unchanged, though perhaps we could add an optional "Public bio" text field that the member could fill out or edit when they are renewing their membership annually.

**Comment by tkimnguyen** [comment]
Ah, I will comment in the issue too.

**Comment by tkimnguyen** [comment]
from discussion in the issue

- The plone.org profiles e.g. http://plone.org/profile/tkimnguyen are the thing for members to maintain actively, so can we display that profile information in the FoundationMember view somehow?
- For each of the contact info fields, do you think it's overkill to let the person to indicate whether it should be publicly visible?

**Comment by tkimnguyen** [comment]
thx @hvelarde! 

@yleclanche it's ok if you are too busy to get to this in the next few days; just let me know. There is the sticky point of whether we can merge any of the code you wrote if you haven't yet sent in a contributor agreement. Could you do this and let me know when it is done? https://plone.org/foundation/contributors-agreement you just have to download it, sign it electronically, and email it to the address shown.

**Comment by yleclanche** [comment]
Thanks for the review @hvelarde 
@tkimnguyen I just sent the contributor agreement. Sorry for the delay.

**Comment by tkimnguyen** [comment]
Oh please @yleclanche, that wasn't a delay... MINE was a delay :) Do think you have time to do more work on this? If you don't, that's perfectly ok.

**Comment by yleclanche** [comment]
I could have filled my contributor agreement a long time ago, so I guess it's a draw ;)

And yes, I have some time to work on this.
For the merit field, another solution would be to add a checkbox to let the user decide the visibility (not visible by default).

> * The plone.org profiles e.g. http://plone.org/profile/tkimnguyen are the thing for members to maintain actively, so can we display that profile information in the FoundationMember view somehow? e.g. if we have the Github user ID value, the profile URL is https://plone.org/profile/GITHUBID

Yes, with the profile id, we could get more information from there.

> * For each of the contact info fields, do you think it's overkill to let the person to indicate whether it should be publicly visible?

Why not.

That's a lot of possibility, but I feel this is not a decision for me to make ;)

**Comment by tkimnguyen** [comment]
All right – since you are doing the work, I figure you have (a lot of) say :) 

I think it's best not to open the Merit visibility can of worms because it means two thing to keep updated. Plone already has that problem, so let's avoid it in this case :) Since your code already asks for the GitHub ID, we have the URL for the Plone.org profile.

Adding a checkbox to let the person allow publishing of their email address would be good. I don't think it's necessary to add a checkbox for the other contact methods as they are by nature already public: GitHub, Twitter, Facebook, LinkedIn, website.

**Comment by yleclanche** [comment]
Yes, duplicating data is a bad idea... In my opinion, we should just add the github field (or rename it 'login id' ?) and get information from profile pages. Or simply redirect the user to the profile page ?
For the email, we should add the visibility checkbox in the profile page.


There is another solution, but it's more complicated and it has some risks : 
In theory, profile pages already have the information of whether the user is a foundation member or not (with the badges system).
So instead of displaying a listing of foundation content type here : [](https://plone.org/foundation/members), we could create a new view which will show all members who have the badge. When a user clicks on a member, we simply redirect to the profile page.

Risks / issues : 

- Some foundation member do not have the badge.
- Maybe some foundation member may not even have a profile page ?
- There is no badge for emeritus members : https://plone.org/foundation/members/emeritus-members/emeritus so we would need to create one and give it to all of them.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Comment by tkimnguyen** [comment]
What happened is this went from small changes to bigger questions that I am not comfortable being the only one commenting on.

**Comment by tkimnguyen** [comment]
@sneridagh @ericof will we be carrying these profile pages forward into the new Plone 6 plone.org?

**Comment by ericof** [comment]
@tkimnguyen Yes, we will. There is already a Foundation Member content type on the new repo

**Comment by tkimnguyen** [comment]
@ericof so we should compare and carry over the missing changes to the new repo?

**Pull request closed without merging**
